# %player% %check% %component% %info% %vl% %vlLimit%

vlLimit: 100 # to ban
vlReset: 15 # reset per minute
alertMsg: "&9&l[MX] &e%player% &8>>&c %check% &7(&c%component%&7) &8%info% &f[%vl%/%vlLimit%]"

unusual: "&9&l[MX] &e%player% &8>>&6 Playing suspiciously"
suspected: "&9&l[MX] &e%player% &8>>&4 Looks like a cheater!"

banCommand: "ban %player% 1d Unfair advantage"

# "NONE" - disable bypass
bypass: "mx.bypass"
bcMsg: "&c&l[MX]&f %message%"
punishEffect: false

# Whether to include mob targeting in anticheat checks
checkMobs: false